# TJS-008 — Publication Lifecycle

**Status:** Draft

**Specification ID:** TJS-008

**Author:** SvitloSk Project

---

# 1. Purpose

This specification defines the lifecycle of Telegram Journal Publications generated by the SvitloSk Publication Engine.

It establishes when Publications are created, updated and removed, ensuring deterministic behaviour of the Telegram Journal throughout the reporting day.

This document is normative.

---

# 2. Scope

This specification applies to:

- daily Publication generation;
- Publication updates;
- Tomorrow Publications;
- Publication ordering;
- Publication lifecycle;
- Telegram Journal stability.

---

# 3. Publication Cycle

The Telegram Journal SHALL follow one daily publication cycle.

The cycle consists of:

1. generation of the Today's Package;
2. publication of Today's Posts;
3. monitoring Dataset updates;
4. updating changed Publications;
5. generation of Tomorrow Publications;
6. removal of obsolete Tomorrow Publications.

---

# 4. Daily Publication Package

The Today's Package SHALL contain one Publication for each Territory containing operational information.

The package MAY contain:

- City Today;
- District Today.

Territories without information SHALL NOT produce Publications.

---

# 5. Tomorrow Publication Package

Tomorrow Publications SHALL form a separate Publication Package.

The package MAY contain:

- City Tomorrow;
- District Tomorrow.

Tomorrow Publications SHALL be temporary.

---

# 6. Publication Windows

The Publication Engine SHALL operate according to the following publication windows.

| Window | Purpose |
|---------|---------|
| approximately 05:00 | Generate Today's Package |
| approximately 12:00 | Begin generating Tomorrow Publications when data becomes available |
| throughout the day | Update Publications after Dataset changes |
| next day approximately 05:00 | Remove obsolete Tomorrow Publications |

The exact execution time MAY vary depending on deployment configuration.

---

# 7. Event-driven Publication Principle

Publication updates SHALL occur only after a new normalized Dataset becomes available.

Time alone SHALL NOT trigger Publication updates.

---

# 8. Stable Journal Principle

The Telegram Journal SHALL remain visually stable throughout the reporting day.

Existing Publications SHALL be updated in place whenever possible.

Publications SHALL NOT be deleted and recreated solely because their content has changed.

Deletion SHALL occur only when the lifecycle of a Publication has ended.

Examples include:

- Tomorrow Publications;
- obsolete Publications replaced due to Territory restructuring.

---

# 9. Deterministic Daily Journal Principle

Two identical normalized Datasets SHALL always generate identical Telegram Journals.

Publication order, formatting and content SHALL remain deterministic.

---

# 10. Non-destructive Update Principle

Updates SHOULD modify existing Publications instead of replacing them.

Replacing an existing Publication SHALL be considered a last resort.

---

# 11. Update Policy

A Publication SHALL be updated only when:

- the normalized Dataset changes; or
- the Rendering Rules change.

No other event SHALL trigger Publication updates.

---

# 12. Tomorrow Publication Lifecycle

Tomorrow Publications SHALL:

- appear only after Tomorrow information becomes available;
- remain visible until the next daily publication cycle;
- be deleted automatically after becoming obsolete.

Tomorrow Publications SHALL NOT become part of the permanent Telegram Journal.

---

# 13. Manual Publications

Manual Publications created by administrators SHALL remain outside the scope of automatic lifecycle management.

The Publication Engine SHALL NOT:

- edit them;
- delete them;
- reorder them.

---

# 14. Image Publications

Image Publications published manually SHALL remain outside the automatic lifecycle.

Examples include:

- outage charts;
- schedule graphics;
- announcements;
- promotional graphics.

The Publication Engine SHALL NOT modify or remove Image Publications.

---

# 15. Publication Session

A Publication Session is one execution of the Publication Engine producing a complete Telegram Journal state from one normalized Dataset.

Each Publication Session SHALL produce a consistent Journal state.

---

# 16. Daily Lifecycle

```text
                    00:00
                      │
                      ▼
            Waiting for daily generation
                      │
                      ▼
                 ≈ 05:00
                      │
                      ▼
         Generate Today's Package
                      │
                      ▼
          Publish Today's Posts
                      │
                      ▼
        Monitor normalized Dataset
                      │
             Dataset changed?
              ┌────────┴────────┐
              │                 │
             No                Yes
              │                 │
              ▼                 ▼
          Do nothing      Update changed Posts
              │
              ▼
                 ≈ 12:00
                      │
                      ▼
        Generate Tomorrow Package
                      │
                      ▼
        Publish Tomorrow Posts
                      │
                      ▼
            Next day ≈ 05:00
                      │
                      ▼
     Delete obsolete Tomorrow Posts
                      │
                      ▼
      Generate new Today's Package
```

---

# 17. Telegram Journal Architecture

```text
                Official Sources
                       │
                       ▼
                    Parser
                       │
                       ▼
              Normalized Dataset
                       │
                       ▼
              Publication Engine
                       │
             Canonical Rendering
                       │
                       ▼
               Telegram Journal
                       │
        ┌──────────────┼──────────────┐
        │              │              │
        ▼              ▼              ▼
 Today's Package   Tomorrow Package   Manual Posts
        │              │              │
 Updated on        Deleted next       Never touched
 Dataset change        day            by Publisher
```

---

# 18. References

Depends on:

- SSP-002 — Parser
- SSP-003 — Publication Engine
- TJS-005 — Message Templates
- TJS-006 — Rendering Rules
- TJS-007 — Channel Management
- DATA_MODEL.md
- TERRITORIAL_MODEL.md

Referenced by:

- future Scheduler implementation
- future Telegram Publisher implementation

---

End of Specification.
